name: after-push checks
run-name: checks
on:
  workflow_dispatch:
  push:
jobs:
  Checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9.13"
          architecture: x64
        env:
          RUNNER_TOOL_CACHE: /opt/hostedtoolcache
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install prospector[with_everything] pytest numpy matplotlib pandas bs4 openpyxl
      - name: unit-tests
        run:
          pytest
      - name: linter
        run:
          prospector --profile .prospector.yaml
